config/routes.rb
Rails.application.routes.draw do
	root 'welcome#desk_board'
  
  resources :welcome

  devise_for :users, controllers: { registrations: 'registrations'}


  devise_for :admins, controllers: { registrations: 'registrations' }
  
  namespace :admin do
  	resources :users 
  	resources :admins 
  	resources :leaves 
    resources :leave_types
  end
  
  resources :users
  resources :leaves do
      member do
        get 'approve'
        get 'reject'
      end
    end
end

app/controllers/admin/leave_types_controller.rb
class Admin::LeaveTypesController < ApplicationController
	before_action :set_leave_type, only: [:edit, :update]
  before_action :find_admin
  
	def index
		@leave_type = LeaveType.all
	end

	def new
		@leave_type = LeaveType.new
	end

	def edit
	end

	def create
   	@leave_type = LeaveType.new(leave_type_params)
		respond_to do |format|
      if @leave_type.save
        format.html { redirect_to admin_leave_types_url, notice: 'Leave Type was successfully created.' }
        format.json { render :show, status: :created, location: @leave_type }
      else
        format.html { render :new }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
	end

	def update
    respond_to do |format|
      if @leave_type.update(leave_type_params)
        format.html { redirect_to admin_leave_types_url, notice: 'Leave Type was successfully updated.' }
        format.json { render :admin_leave_types, status: :ok, location: @leave_type }
      else
        format.html { render :edit }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
  end

	 def destroy
    @leave_type = LeaveType.find(params[:id])
    @leave_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_leave_types_url, notice: 'Leave type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def leave_type_params
    params.require(:leave_type).permit(:name, :description, :active)
  end

  def set_leave_type
    @leave_type = LeaveType.find(params[:id])
  end
	
   def find_admin
    unless current_admin.present? 
      respond_to do |format|
          format.html { redirect_to new_admin_session, notice: 'please first sign in' }
      end
    end
  end
end

app/helpers/admin/leave_types_helper.rb
module Admin::LeaveTypesHelper
end

app/views/admin/leave_types/_form.html.erb
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <%= form_for [:admin, @leave_type] do |f| %>
        <fieldset>
          <div class="form-group" >
            <label class="col-lg-6 control-label ">name:</label>
            <div class="col-lg-6 ">
              <%= f.text_field :name, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>

          <div class="form-group" >
            <label class="col-lg-6 control-label ">Description:</label>
            <div class="col-lg-6 ">
              <%= f.text_field :description, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>

          <div class="form-group" >
            <label class="col-lg-6 control-label ">active:</label>
            <div class="col-lg-6 ">
              <%= f.text_field :active, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>
      </fieldset>
      </br>
      <button type="f.submit" class="btn btn-primary">Create Leave Type</button>
    <% end %>
  </div>
</div>
</br>

app/views/admin/leave_types/edit.html.erb
<h1>Editing Leave Type</h1>

<%= render 'form', admin: @leave_type %>

<%= link_to 'Back', admin_leave_types_path %>

app/views/admin/leave_types/index.html.erb
<html>
  <head>
    <style >
   .row {
    margin-right: -15px;
    margin-left: -15px;
    font-size: 30px;
}
     </style>
  
  </head>

  <body>
<div class="container">
  <div class="row">
    <div class="col-sm-6 text-left"> Leave Type </div>
    <div class="col-sm-6 text-right"><%= link_to "New",new_admin_leave_type_path %></div><br />
  </div>
  <div class="table-responsive">          
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Active</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @leave_type.each do |leave| id = leave.id %>
      <tr>
        <td><%= leave.name %></td>
        <td><%= leave.description %></td>
        <td><%= leave.active %></td>
        <td><%= link_to 'Destroy', admin_leave_type_path(id),class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Update' , edit_admin_leave_type_path(id),class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
 
  </body>

</html>

app/views/admin/leave_types/new.html.erb
<h2>New Leave Type</h2>

<%= render 'form', admin: @leave_type %>

<%= link_to 'Back',admin_leave_types_path %>
</br>