config/routes.rb
Rails.application.routes.draw do
	root 'welcome#desk_board'
  
  resources :welcome

  devise_for :users, controllers: { registrations: 'registrations'}


  devise_for :admins, controllers: { registrations: 'registrations' }
  
  namespace :admin do
  	resources :users 
  	resources :admins 
  	resources :leaves 
    resources :leave_types
  end
  
  resources :users
  resources :leaves do
      member do
        get 'approve'
        get 'reject'
      end
    end
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :user
  belongs_to :leave_type
  validate :date_cannot_be_in_the_past
  validates :user_id, :start_at, :end_at, :leave_type_id, :description, presence: true

  after_create :send_admin_mail 

  def date_cannot_be_in_the_past
  	if start_at > end_at
  		errors.add(:end_at, "can't be in the past")
  	end
    if  start_at < Date.today 
      errors.add(:start_at, "can't be in the past")
    end
    if  end_at < Date.today
    	errors.add(:end_at, "can't be in the past")
    end
  end  

  def send_admin_mail
    AdminMailer.leave_mail(user).deliver
  end
  
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
	has_many :leaves
end

app/controllers/admin/leaves_controller.rb
class Admin::LeavesController < ApplicationController
	before_action :find_admin
	def index
		@leave = Leave.order("updated_at DESC")
	end

  def leave_params
    params.require(:leave).permit(:status)
  end

  def find_admin
    unless current_admin.present? 
      respond_to do |format|
          format.html { redirect_to new_admin_session, notice: 'please first sign in' }
      end
    end
  end

end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController

    after_filter :send_admin_mail, only: [:update]
    after_filter :send_user_mail, only: [:approve, :reject]
	def index
    @leave = Leave.order("updated_at DESC").where user_id: current_user.id 
	end
	def new
		@leave=Leave.new
	end

  def edit
    @leave = Leave.find(params[:id])
  end

  def update
    @leave = Leave.find(params[:id])
    respond_to do |format|
      if @leave.update(leave_params)
        format.html { redirect_to leaves_url, notice: 'leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave }
      else
        format.html { render :edit }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

def approve
  @leave = Leave.find(params[:id])
  @leave.status="Approved"
  @leave.save
  respond_to do |format|
    format.html { redirect_to admin_leaves_url, notice: 'Status was successfully updated.' }
  end
end

 def reject
  @leave = Leave.find(params[:id])
  @leave.status="Rejected"
  @leave.save
   respond_to do |format|
    format.html { redirect_to admin_leaves_url, notice: 'Status was successfully updated.' }
  end
 end

	def create
    @leave = current_user.leaves.new(leave_params)
    respond_to do |format|
      if @leave.save
        format.html { redirect_to leaves_url, notice: 'Leave was successfully created.' }
        format.json { render :show, status: :created, location: @leave }
      else
        format.html { render :new }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
	end

  def destroy
    @leave = Leave.find(params[:id])
    @leave.destroy
    respond_to do |format|
      format.html { redirect_to leaves_url, notice: 'leave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
	def leave_params
     params.require(:leave).permit(:description, :start_at, :end_at, :user_id, :leave_type_id, :leave_for)
  end

  def send_admin_mail
    AdminMailer.leave_update_mail(current_user).deliver
  end 

  def send_user_mail
    @leave = Leave.find(params[:id])
    UserMailer.leave_status_email(@leave.user).deliver
  end 
  
end

app/helpers/admin/leaves_helper.rb
module Admin::LeavesHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_form.html.erb
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
     <%= form_for [leave] do |f| %>
        <fieldset>
          <div class="form-group" >
            <label class="col-lg-6 control-label ">Type:</label>
            <%= f.select :leave_type_id, options_for_select(LeaveType.all.collect {|t| [t.name, t.id]}), :prompt => 'Select' %>
          </div>
          <div class="form-group" >
            <label class="col-lg-6 control-label ">Description:</label>
            <div class="col-lg-6 ">
              <%= f.text_field :description, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>
           <div class="form-group" >
            <label class="col-lg-6 control-label ">Start Date:</label>
            <div class="col-lg-6 ">
              <%= f.date_field :start_at, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>
           <div class="form-group" >
            <label class="col-lg-6 control-label ">End Date:</label>
            <div class="col-lg-6 ">
              <%= f.date_field :end_at, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>

          <div class="form-group" >
            <label class="col-lg-6 control-label ">Leave for:</label>
            <%= f.select :leave_for, options_for_select(["Select One", "Full day", "Half day"],:disabled => ["Select One"], :selected => leave.leave_for), :class => 'genForm_dropBox' %>
          </div>

      </fieldset>
      </br>
      <button type="f.submit" class="btn btn-primary">Create Leave</button>
    <% end %>
  </div>
</div>
</br>

app/views/leaves/edit.html.erb
<h2>Edit leave</h2>
<%= render 'form',leave: @leave %>
<%= link_to 'Back', users_path %>
</br>

app/views/leaves/index.html.erb
  <head>
    <style >
   .row {
    margin-right: -15px;
    margin-left: -15px;
    font-size: 30px;
}
     </style>
  </head>

  <div class="container">
  <div class="row">
    <div class="col-sm-6 text-left"> Leaves </div>
    <div class="col-sm-6 text-right"><%=link_to "New leave", new_leave_path %></div><br />
  </div>
  <div class="table-responsive">          
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Leave Id </th>
        <th>Leave For</th>
      	<th>Leave Type</th>
        <th>Description</th>
        <th>Start At</th>
        <th>end At</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @leave.each do |leave| id = leave.id %>
      <tr>
        <td><%= leave.id %></td>
        <td><%= leave.leave_for %></td>
 				<td><%= leave.leave_type.name %></td>
        <td><%= leave.description%></td>
        <td><%= leave.start_at.strftime("%d/%m/%Y") %></td>
        <td><%= leave.end_at.strftime("%d/%m/%Y") %></td>
        <td><%= leave.status %></td>
         <td><%= link_to 'Destroy', leave_path(id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        <%= link_to 'Edit', edit_leave_path(id), class: 'btn btn-warning btn-sm' if leave.status !="Approved" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
<br>

app/views/leaves/new.html.erb
 <h2>New leave</h2>
<%= render 'form',leave: @leave %>
<%= link_to 'Back', users_path %>
</br>