config/routes.rb
Rails.application.routes.draw do
	root 'welcome#desk_board'
  
  resources :welcome

  devise_for :users, controllers: { registrations: 'registrations'}


  devise_for :admins, controllers: { registrations: 'registrations' }
  
  namespace :admin do
  	resources :users 
  	resources :admins 
  	resources :leaves 
    resources :leave_types
  end
  
  resources :users
  resources :leaves do
      member do
        get 'approve'
        get 'reject'
      end
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
 after_create :send_admin_mail 

 attr_accessor :password_token

  def send_admin_mail
    AdminMailer.welcome_email(self).deliver
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :user
  belongs_to :leave_type
  validate :date_cannot_be_in_the_past
  validates :user_id, :start_at, :end_at, :leave_type_id, :description, presence: true

  after_create :send_admin_mail 

  def date_cannot_be_in_the_past
  	if start_at > end_at
  		errors.add(:end_at, "can't be in the past")
  	end
    if  start_at < Date.today 
      errors.add(:start_at, "can't be in the past")
    end
    if  end_at < Date.today
    	errors.add(:end_at, "can't be in the past")
    end
  end  

  def send_admin_mail
    AdminMailer.leave_mail(user).deliver
  end
  
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
	has_many :leaves
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :send_admin_mail 
  has_many :leaves

  attr_accessor :password_token

  def send_admin_mail
    UserMailer.welcome_email(self).deliver
  end

  def name
    (first_name.blank? && last_name.blank?) ? "NA" : "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :find_admin

	def index
		@admin = Admin.all
	end

	def new
		@admin = Admin.new
	end

	def create
   	@admin = Admin.new(admin_params)

    @admin.password = rand(11111111..99999999)

    raw, enc = Devise.token_generator.generate(Admin, :reset_password_token)
    @admin.reset_password_token = enc
    @admin.reset_password_sent_at = Time.now.utc
    @admin.password_token = raw

    respond_to do |format|
      if @admin.save
        format.html { redirect_to admin_admins_url, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admin_admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin_params
    params.require(:admin).permit(:email, :password)
  end

  def find_admin
    unless current_admin.present? 
      respond_to do |format|
          format.html { redirect_to new_admin_session, notice: 'please first sign in' }
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :find_admin
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.password = rand(11111111..99999999)

    raw, enc = Devise.token_generator.generate(User, :reset_password_token)
    @user.reset_password_token = enc
    @user.reset_password_sent_at = Time.now.utc
    @user.password_token = raw

    respond_to do |format|
      if @user.save
         format.html { redirect_to admin_users_url, notice: 'user was successfully created.' }
         format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

   def user_params
     params.require(:user).permit(:email, :password)
  end

   def find_admin
    unless current_admin.present? 
      respond_to do |format|
          format.html { redirect_to new_admin_session, notice: 'please first sign in' }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

    def update_sanitized_params
       devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
       devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:name, :email, :password)}
       devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :contact_no, :address1, :address2)}
    end

end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController

    after_filter :send_admin_mail, only: [:update]
    after_filter :send_user_mail, only: [:approve, :reject]
	def index
    @leave = Leave.order("updated_at DESC").where user_id: current_user.id 
	end
	def new
		@leave=Leave.new
	end

  def edit
    @leave = Leave.find(params[:id])
  end

  def update
    @leave = Leave.find(params[:id])
    respond_to do |format|
      if @leave.update(leave_params)
        format.html { redirect_to leaves_url, notice: 'leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave }
      else
        format.html { render :edit }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

def approve
  @leave = Leave.find(params[:id])
  @leave.status="Approved"
  @leave.save
  respond_to do |format|
    format.html { redirect_to admin_leaves_url, notice: 'Status was successfully updated.' }
  end
end

 def reject
  @leave = Leave.find(params[:id])
  @leave.status="Rejected"
  @leave.save
   respond_to do |format|
    format.html { redirect_to admin_leaves_url, notice: 'Status was successfully updated.' }
  end
 end

	def create
    @leave = current_user.leaves.new(leave_params)
    respond_to do |format|
      if @leave.save
        format.html { redirect_to leaves_url, notice: 'Leave was successfully created.' }
        format.json { render :show, status: :created, location: @leave }
      else
        format.html { render :new }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
	end

  def destroy
    @leave = Leave.find(params[:id])
    @leave.destroy
    respond_to do |format|
      format.html { redirect_to leaves_url, notice: 'leave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
	def leave_params
     params.require(:leave).permit(:description, :start_at, :end_at, :user_id, :leave_type_id, :leave_for)
  end

  def send_admin_mail
    AdminMailer.leave_update_mail(current_user).deliver
  end 

  def send_user_mail
    @leave = Leave.find(params[:id])
    UserMailer.leave_status_email(@leave.user).deliver
  end 
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def desk_board
	end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/leave_types_helper.rb
module Admin::LeaveTypesHelper
end

app/helpers/admin/leaves_helper.rb
module Admin::LeavesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admins/_form.html.erb
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
     <%= form_for [:admin, @admin] do |f| %>
        <fieldset>
          <div class="form-group" >
            <label class="col-lg-6 control-label ">Email:</label>
            <div class="col-lg-6 ">
              <%= f.email_field :email, autofocus: true, class: 'form-control input-lg' %>
            </div>
          </div>
      </fieldset>
      </br>
      <button type="f.submit" class="btn btn-primary">Create Admin</button>
    <% end %>
  </div>
</div>
</br>

app/views/admin/admins/index.html.erb
<html>
  <head>
    <style >
   .row {
    margin-right: -15px;
    margin-left: -15px;
    font-size: 30px;
}
     </style>
  
  </head>

  <body>
<div class="container">
  <div class="row">
    <div class="col-sm-6 text-left"> Admins </div>
    <div class="col-sm-6 text-right"><%=link_to "New Admin", new_admin_admin_path %></div><br />
  </div>
  <div class="table-responsive">          
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Contact no.</th>
        <th>Permanent Address</th>
        <th>Temporary Address</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @admin.each do |admin| id = admin.id %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= admin.first_name %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.contact_no %></td>
        <td><%= admin.address1 %></td>
        <td><%= admin.address2 %></td>
        <td><%= link_to 'Destroy', admin_admin_path(id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
 
  </body>

</html>

app/views/admin/admins/new.html.erb
<h2>New admin</h2>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admin_admins_path %>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>

    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    .text-center {
    margin: 0 0 305px;
    padding: 10px 0px;
}


  header .cont {

    margin-bottom: 0px;
  }

    ul {
      padding-top: 14px;
    }

    a{
      padding-left: 12px;
    }
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
  </head>
  <body>
    <header>
    <nav class="navbar navbar-inverse cont">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <!-- <a class="navbar-brand" href="#">Logo</a>
 -->        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
           <% if current_admin.present? %>
          <li><%= link_to "Admins",admin_admins_path %></li>
          <li><%= link_to "Users", admin_users_path %></li>
          <li><%= link_to "Profile", edit_admin_registration_path %></li>
          <li><%= link_to "Leaves",admin_leaves_path %></li>
          <li><%= link_to "Logout", destroy_admin_session_path, :method => 'delete' %></li>
          <% end %>
          <% if current_user.present? %>
          <li><%= link_to "Leave", leaves_path %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
          <% end %>
          </ul>
           <% unless current_admin.present? || current_user.present? %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href= "users/sign_in"<span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
           <% end %>
        </div>
      </div>
    </nav>
    </header>
    <div class="container-fluid ">
      <ul class="nav navbar-nav navbar-right">
        <%= form_tag( :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <%= submit_tag "Search", :name => nil %>
        <% end %>
      </ul>
    </div>
    <div class="text-center" >
      <% if !flash.empty? %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <% if current_admin.present? || current_user.present? %>
      <footer style="text-align: center;">
        Throughout Technologies @2017
      </footer>
    <% end %>

  </body>
</html>